# Generated by Django 4.2 on 2023-06-10 02:50

import apps.product.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=10)),
                ('stock', models.IntegerField(default=1)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=apps.product.models.upload_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
